Internal Server Error: /hospitals/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\doctors_appointment\hospitals\views.py", line 345, in index
    'booking_time': booking.booking_time.strftime('%H:%M') if booking.booking_time else '',
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Booking' object has no attribute 'booking_time'. Did you mean: 'booking_date'?
"GET /hospitals/?section=appointments&format=json HTTP/1.1" 500 108581
Internal Server Error: /hospitals/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\doctors_appointment\hospitals\views.py", line 345, in index
    'booking_time': booking.booking_time.strftime('%H:%M') if booking.booking_time else '',
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Booking' object has no attribute 'booking_time'. Did you mean: 'booking_date'?
"GET /hospitals/?section=appointments&format=json HTTP/1.1" 500 108581
Internal Server Error: /hospitals/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\doctors_appointment\hospitals\views.py", line 345, in index
    'booking_time': booking.booking_time.strftime('%H:%M') if booking.booking_time else '',
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Booking' object has no attribute 'booking_time'. Did you mean: 'booking_date'?
"GET /hospitals/?section=appointments&format=json HTTP/1.1" 500 108581
Internal Server Error: /hospitals/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\doctors_appointment\hospitals\views.py", line 345, in index
    'booking_time': booking.booking_time.strftime('%H:%M') if booking.booking_time else '',
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Booking' object has no attribute 'booking_time'. Did you mean: 'booking_date'?
"GET /hospitals/?section=appointments&format=json HTTP/1.1" 500 108581
Internal Server Error: /hospitals/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\doctors_appointment\hospitals\views.py", line 345, in index
    'booking_time': booking.booking_time.strftime('%H:%M') if booking.booking_time else '',
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Booking' object has no attribute 'booking_time'. Did you mean: 'booking_date'?
"GET /hospitals/?section=appointments&format=json HTTP/1.1" 500 108809
Internal Server Error: /hospitals/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\doctor\doctors_appointment\hospitals\views.py", line 345, in index
    'booking_time': booking.booking_time.strftime('%H:%M') if booking.booking_time else '',
                                                              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Booking' object has no attribute 'booking_time'. Did you mean: 'booking_date'?
"GET /hospitals/?section=appointments&format=json HTTP/1.1" 500 108809
Internal Server Error: /hospitals/completed_appointment/63/
"POST /hospitals/completed_appointment/63/ HTTP/1.1" 500 99
